import {StyleSheet} from 'react-native';
import {Color} from '../../res/Color';

export const styles = StyleSheet.create({
  container: {
    width: '45%',
    backgroundColor: Color.background,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 20,
    paddingTop: 40,
    paddingBottom: 20,
    paddingHorizontal: 20,
    margin: '2%',
  },
  out_of_stock_container: {
    flex: 1,
    position: 'absolute',
    top: 0,
    right: 0,
    left: 0,
    bottom: 0,
    backgroundColor: 'rgba(0,0,0,0.4)',
    zIndex: 2,
    borderRadius: 20,
  },
  out_of_stock_text_container: {
    backgroundColor: Color.outOfStock,
    marginTop: 10,
    padding: 3,
    width: '50%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  out_of_stock: {color: 'white', fontSize: 13},
  promo_container: {
    alignItems: 'center',
    justifyContent: 'center',
    width: 55,
    position: 'absolute',
    top: 0,
    right: 0,
    height: 30,
    backgroundColor: Color.primary,
    borderRadius: 0,
    zIndex: 1,
    borderTopRightRadius: 20,
    borderBottomLeftRadius: 20,
  },
  promo_text_container: {
    width: '100%',
    height: '100%',
    borderTopRightRadius: 20,
    borderBottomLeftRadius: 20,
    justifyContent: 'center',
  },
  image: {width: 90, height: 90},
  lb_container: {flex: 1, width: '100%', marginVertical: 5},
  price_container: {
    flex: 1,
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  line_price: {
    fontSize: 14,
    textDecorationLine: 'line-through',
    color: 'gray',
  },
});
